apiVersion: apps/v1
kind: Deployment
metadata:
  name: "flask-monitor"
spec:
  template:
    spec:
      containers:
      - name: "flask"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"